### ISSUE TITLE
其实没有必要填写各项数据，可以直接获取上一次的打卡信息

### ISSUE THREAD

**Issue by OharaRinneY** [chloceg/hhu-daily-health-common#1]
具体可以看一下我的博客 https://blog.yiheng.moe/code/hhu-health-checkin.html
这样就只需要学号和密码便可以打卡了

**Comment by chloceg** [comment]
嗯嗯，这个可以，后来看了几个repo，我这个算最麻烦的办法了( •̀ ω •́ )y。现在感觉最简单的办法是，模拟登录了之后，selenium模拟点击提交按钮（反正是填充好的表单）。

**Comment by yin1999** [comment]
打卡页面有历史记录，不过开发这个服务的有点懒，都没有限制历史记录的长度，一股脑地将每天的打卡记录全推到前端来。。。之前开发没注意长度限制，64KB的ReadLine缓存都给它存满了。这也算一个小坑吧 -_-

**Comment by yin1999** [comment]
@chloceg 
我帮你把动态获取打卡数据的功能做好了，你可以去clone我fork的仓库测试。用`github secrets`来登录的那个功能我明天可以帮你加进来。`info.ini`暂时保留，作向后兼容。如果觉得ok，请接受我的PR。欢迎提出改进意见

修改的功能也算是来自我自己做的那个版本
